name: Continuous Integration

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    branch-name:
        name: Branch Name
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Echo name
              shell: bash
              env:
                  HEAD_REF: ${{ github.head_ref }}
                  REF_NAME: ${{ github.ref_name }}
              run: |
                  echo "$HEAD_REF"
                  echo "$REF_NAME"
